#!/usr/bin/env bash
set -euo pipefail
umask 077

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION="${PATCHWRIGHT_VERSION:-0.1.0}"
BUILD="${PATCHWRIGHT_BUILD:-1}"
SPARKLE_ACCOUNT="ai.patchwright.app"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ && "$BUILD" =~ ^[1-9][0-9]*$ ]] || { echo "invalid release version or build" >&2; exit 64; }
COMMIT="$(git -C "$ROOT_DIR" rev-parse HEAD)"
TAG_COMMIT="$(git -C "$ROOT_DIR" rev-parse "refs/tags/v$VERSION^{commit}" 2>/dev/null || true)"
[[ "$TAG_COMMIT" == "$COMMIT" ]] || { echo "release tag v$VERSION must resolve to HEAD" >&2; exit 65; }
[[ -z "$(git -C "$ROOT_DIR" status --porcelain)" ]] || { echo "release worktree must be clean" >&2; exit 65; }

ASSEMBLY_OUTPUT="$(PATCHWRIGHT_VERSION="$VERSION" PATCHWRIGHT_BUILD="$BUILD" "$ROOT_DIR/script/build_release_components.sh")"
RELEASE_ROOT="$(printf '%s\n' "$ASSEMBLY_OUTPUT" | sed -n 's/^PATCHWRIGHT_RELEASE_ROOT=//p')"
APP_PATH="$(printf '%s\n' "$ASSEMBLY_OUTPUT" | sed -n 's/^PATCHWRIGHT_APP_PATH=//p')"
PRIVATE_EVIDENCE="$RELEASE_ROOT/private-evidence"
mkdir -p "$RELEASE_ROOT/evidence" "$PRIVATE_EVIDENCE"
"$ROOT_DIR/script/assert_release_assembly.sh" "$RELEASE_ROOT/evidence/assembly.json"
"$ROOT_DIR/script/sign_release.sh" "$APP_PATH"
"$ROOT_DIR/script/notarize_release.sh" "$APP_PATH" "$RELEASE_ROOT/evidence/notary-app.json" "$PRIVATE_EVIDENCE" app
DMG_PATH="$RELEASE_ROOT/Patchwright-$VERSION.dmg"
"$ROOT_DIR/script/create_dmg.sh" "$APP_PATH" "$DMG_PATH"
"$ROOT_DIR/script/notarize_release.sh" "$DMG_PATH" "$RELEASE_ROOT/evidence/notary-dmg.json" "$PRIVATE_EVIDENCE" dmg
"$ROOT_DIR/script/verify_distribution.sh" "$DMG_PATH"
ARTIFACT_SHA256="$(shasum -a 256 "$DMG_PATH" | awk '{print $1}')"
printf '%s  %s\n' "$ARTIFACT_SHA256" "$(basename "$DMG_PATH")" >"$DMG_PATH.sha256"

SPARKLE_BIN="$ROOT_DIR/.build/artifacts/sparkle/Sparkle/bin"
APPCAST_STAGE="$(mktemp -d "${TMPDIR:-/tmp}/patchwright-appcast.XXXXXX")"
trap '/usr/bin/trash "$APPCAST_STAGE" >/dev/null 2>&1 || true' EXIT
/usr/bin/ditto "$DMG_PATH" "$APPCAST_STAGE/$(basename "$DMG_PATH")"
"$SPARKLE_BIN/generate_appcast" --account "$SPARKLE_ACCOUNT" \
  --download-url-prefix "https://github.com/s1korrrr/patchwright/releases/download/v$VERSION" \
  --link "https://github.com/s1korrrr/patchwright/releases/tag/v$VERSION" --versions "$BUILD" --maximum-deltas 0 \
  -o "$APPCAST_STAGE/appcast.xml" "$APPCAST_STAGE"
APPCAST_PATH="$RELEASE_ROOT/appcast.xml"
/usr/bin/ditto "$APPCAST_STAGE/appcast.xml" "$APPCAST_PATH"
"$SPARKLE_BIN/sign_update" --account "$SPARKLE_ACCOUNT" --verify "$APPCAST_PATH"

PATCHWRIGHT_ARTIFACT_SHA256="$ARTIFACT_SHA256" "$ROOT_DIR/script/generate_release_metadata.sh" --phase metadata --app "$APP_PATH" --output-root "$RELEASE_ROOT"
# Candidate and gate JSON are generated by the package evidence stage before this freeze.
"$ROOT_DIR/script/generate_release_metadata.sh" --phase checksums --output-root "$RELEASE_ROOT"
CANDIDATE_MANIFEST="$RELEASE_ROOT/evidence/notarized-candidate.json"
"$ROOT_DIR/script/verify_release_evidence.py" candidate --candidate "$CANDIDATE_MANIFEST" --repo "$ROOT_DIR"
printf 'PATCHWRIGHT_RELEASE_ROOT=%s\nPATCHWRIGHT_APP_PATH=%s\nPATCHWRIGHT_DMG_PATH=%s\n' "$RELEASE_ROOT" "$APP_PATH" "$DMG_PATH"
printf 'PATCHWRIGHT_CANDIDATE_MANIFEST=%s\nPATCHWRIGHT_ARTIFACT_SHA256=%s\nPATCHWRIGHT_STATUS=notarized-candidate\n' "$CANDIDATE_MANIFEST" "$ARTIFACT_SHA256"
